services:
  web:
    build:
      context: .
    ports:
      - 5000:5000
      - 465:465
    volumes:
      - ${CLOCKIFY_INVOICE_HOME}/clockify-invoice-config.json:/invoices/clockify-invoice-config.json
      - ${CLOCKIFY_INVOICE_HOME}/db.db:/invoices/db.db
