GET_USER = {
    "id": "1234ABCD",
    "email": "test.email@gmail.com",
    "name": "Test User",
    "memberships": [],
    "profilePicture": "https://img.clockify.me/no-user-image.png",
    "activeWorkspace": "test-active-workspace",
    "defaultWorkspace": "test-default-workspace",
    "settings": {
        "weekStart": "MONDAY",
        "timeZone": "Australia/Brisbane",
        "timeFormat": "HOUR24",
        "dateFormat": "DD/MM/YYYY",
        "sendNewsletter": False,
        "weeklyUpdates": True,
        "longRunning": True,
        "scheduledReports": True,
        "approval": True,
        "pto": True,
        "alerts": True,
        "reminders": True,
        "timeTrackingManual": False,
        "summaryReportSettings": {"group": "Project", "subgroup": "Time Entry"},
        "isCompactViewOn": False,
        "dashboardSelection": "ME",
        "dashboardViewType": "PROJECT",
        "dashboardPinToTop": False,
        "projectListCollapse": 50,
        "collapseAllProjectLists": False,
        "groupSimilarEntriesDisabled": False,
        "myStartOfDay": "09:00",
        "projectPickerTaskFilter": False,
        "lang": "EN",
        "multiFactorEnabled": False,
        "theme": "DARK",
        "scheduling": True,
        "onboarding": True,
        "showOnlyWorkingDays": False,
    },
    "status": "ACTIVE",
    "customFields": [],
}
